name=ESP32P4-Camera
version=0.1.0
author=Prince223889
maintainer=Prince223889
sentence=Small Arduino camera layer for ESP32-P4 MIPI-CSI cameras
paragraph=Small Arduino camera layer for ESP32-P4 MIPI-CSI cameras Built for Arduino-ESP32 and designed for reusable embedded projects.
category=Sensors
url=https://github.com/Prince223889/ESP32P4-Camera
architectures=esp32
